"""correct table tasks

Revision ID: 10d44aad7129
Revises: 23829d621f24
Create Date: 2024-02-06 13:46:07.828180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "10d44aad7129"
down_revision: Union[str, None] = "23829d621f24"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sessions", sa.Column("expires_in", sa.DateTime(), nullable=False)
    )
    op.add_column(
        "tasks",
        sa.Column(
            "done",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "done")
    op.drop_column("sessions", "expires_in")
    # ### end Alembic commands ###
