"""add column expires_in into table sessions

Revision ID: 23829d621f24
Revises: 60890d3cd3be
Create Date: 2024-02-04 13:56:17.794483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "23829d621f24"
down_revision: Union[str, None] = "60890d3cd3be"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sessions", sa.Column("expires_in", sa.DateTime(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sessions", "expires_in")
    # ### end Alembic commands ###
