"""email is not unique field

Revision ID: 5834640c0442
Revises: 2f3e7521befb
Create Date: 2024-02-03 18:31:59.825876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5834640c0442"
down_revision: Union[str, None] = "2f3e7521befb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_email_key", "users", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("users_email_key", "users", ["email"])
    # ### end Alembic commands ###
